
obj-y += _ddr_delaychain_check.o
obj-y += _ddr_freq_change.o
obj-y += _GL5202_BDMA0_TRANSFER.o
obj-y += _GL5202_data_compare_byte.o
obj-y += _GL5202_DDR3_init.o
obj-y += _GL5202_DDR_CAP_DETECT.o
obj-y += _GL5202_DDR_init_main.o
obj-y += _GL5202_DelayChain_Scan.o
obj-y += _test_data_init.o
obj-y += _timing_parameter_genarate.o

