#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# Lipeng<lipeng@actions-semi.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_VIDEO_OWL_DE_S900) += de_s900.o
obj-$(CONFIG_VIDEO_OWL_DE_S700) += de_s700.o
