#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# Lipeng<lipeng@actions-semi.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_VIDEO_OWL_LCD) += panel-glp.o
obj-$(CONFIG_VIDEO_OWL_EDP) += panel-gep.o
obj-$(CONFIG_VIDEO_OWL_HDMI) += panel-ghp.o
obj-$(CONFIG_VIDEO_OWL_CVBS) += panel-gcp.o
obj-$(CONFIG_VIDEO_OWL_DSI) += panel-gmp.o
obj-$(CONFIG_VIDEO_OWL_DUMMY) += panel-gdp.o

obj-$(CONFIG_VIDEO_OWL_DSI) += panel-lq055t3sx02.o
obj-$(CONFIG_VIDEO_OWL_DSI) += panel-amoled.o
obj-$(CONFIG_VIDEO_OWL_EDP) += panel-tc358860.o
