/*
 * (C) Copyright 2012
 * Actions Semi .Inc
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __ASM_ISP_H
#define __ASM_ISP_H

#define ISP_BASE				0xB0270000
#define ISP_CB_TIME				(ISP_BASE + 0x00)
#define ISP_ENABLE				(ISP_BASE + 0x10)
#define ISP_CTL					(ISP_BASE + 0x20)
#define ISP_CHANNEL_1_STATE			(ISP_BASE + 0x24)
#define ISP_CHANNEL_1_BA_OFFSET			(ISP_BASE + 0x28)
#define ISP_CHANNEL_1_ROW_RANGE			(ISP_BASE + 0x2C)
#define ISP_CHANNEL_1_COL_RANGE			(ISP_BASE + 0x30)
#define ISP_CHANNEL_1_ADDR0			(ISP_BASE + 0x34)
#define ISP_CHANNEL_1_ADDR1			(ISP_BASE + 0x38)
#define ISP_CHANNEL_1_ADDR2			(ISP_BASE + 0x3C)
#define ISP_CHANNEL_1_ADDR3			(ISP_BASE + 0x40)
#define ISP_CHANNEL_1_ADDR4			(ISP_BASE + 0x44)
#define ISP_CHANNEL_1_ADDR5			(ISP_BASE + 0x48)
#define ISP_CHANNEL_1_ADDR6			(ISP_BASE + 0x4C)
#define ISP_CHANNEL_1_ADDR7			(ISP_BASE + 0x50)
#define VNC_LUT_PORT				(ISP_BASE + 0x54)
#define VNC_RST					(ISP_BASE + 0x58)
#define ISP_LSC_LUT_PORT			(ISP_BASE + 0x60)
#define ISP_LSC_PIX_INC			(ISP_BASE + 0x64)
#define ISP_LSC_SCALING			(ISP_BASE + 0x68)
#define ISP_LSC_CENTER0			(ISP_BASE + 0x6C)
#define ISP_LSC_CENTER1			(ISP_BASE + 0x70)
#define ISP_LSC_RST			(ISP_BASE + 0x74)
#define ISP_NR_CONTROL			(ISP_BASE + 0x80)
#define ISP_DPC_THRESHOLD		(ISP_BASE + 0x88)
#define ISP_CG_B_GAIN			(ISP_BASE + 0x90)
#define ISP_CG_G_GAIN			(ISP_BASE + 0x94)
#define ISP_CG_R_GAIN			(ISP_BASE + 0x98)
#define ISP_STAT_REGION_Y		(ISP_BASE + 0xA0)
#define ISP_STAT_REGION_X		(ISP_BASE + 0xA4)
#define ISP_STAT_HIST_Y			(ISP_BASE + 0xA8)
#define ISP_STAT_HIST_X			(ISP_BASE + 0xAC)
#define ISP_WB_THRESHOLD		(ISP_BASE + 0xB0)
#define ISP_CSC_OFFSET1			(ISP_BASE + 0xC0)
#define ISP_CSC_OFFSET2			(ISP_BASE + 0xC4)
#define ISP_CSC_OFFSET3			(ISP_BASE + 0xC8)
#define ISP_CSC_Y_R			(ISP_BASE + 0xCC)
#define ISP_CSC_Y_G			(ISP_BASE + 0xD0)
#define ISP_CSC_Y_B			(ISP_BASE + 0xD4)
#define ISP_CSC_CB_R			(ISP_BASE + 0xD8)
#define ISP_CSC_CB_G			(ISP_BASE + 0xDC)
#define ISP_CSC_CB_B			(ISP_BASE + 0xE0)
#define ISP_CSC_CR_R			(ISP_BASE + 0xE4)
#define ISP_CSC_CR_G			(ISP_BASE + 0xE8)
#define ISP_CSC_CR_B			(ISP_BASE + 0xEC)
#define ISP_CSC_CONTROL			(ISP_BASE + 0xF0)
#define ISP_GC_COEFF_0			(ISP_BASE + 0x100)
#define ISP_GC_COEFF_1			(ISP_BASE + 0x104)
#define ISP_GC_COEFF_2			(ISP_BASE + 0x108)
#define ISP_GC_COEFF_3			(ISP_BASE + 0x10C)
#define ISP_GC_COEFF_4			(ISP_BASE + 0x110)
#define ISP_GC_COEFF_5			(ISP_BASE + 0x114)
#define ISP_GC_COEFF_6			(ISP_BASE + 0x118)
#define ISP_GC_COEFF_7			(ISP_BASE + 0x11C)
#define ISP_GC_COEFF_8			(ISP_BASE + 0x120)
#define ISP_GC_COEFF_9			(ISP_BASE + 0x124)
#define ISP_GC_COEFF_10			(ISP_BASE + 0x128)
#define ISP_GC_COEFF_11			(ISP_BASE + 0x12C)
#define ISP_GC_COEFF_12			(ISP_BASE + 0x130)
#define ISP_GC_COEFF_13			(ISP_BASE + 0x134)
#define ISP_GC_COEFF_14			(ISP_BASE + 0x138)
#define ISP_GC_COEFF_15			(ISP_BASE + 0x13C)
#define ISP_OUT_FMT			(ISP_BASE + 0x148)
#define ISP_OUT_ADDRY			(ISP_BASE + 0x14C)
#define ISP_OUT_ADDRU			(ISP_BASE + 0x150)
#define ISP_OUT_ADDRV			(ISP_BASE + 0x154)
#define ISP_OUT_ADDR1UV			(ISP_BASE + 0x158)
#define ISP_STAT_ADDR			(ISP_BASE + 0x160)
#define ISP_COLOR_REPLACE1			(ISP_BASE + 0x170)
#define ISP_COLOR_REPLACE2			(ISP_BASE + 0x174)
#define ISP_COLOR_REPLACE3			(ISP_BASE + 0x178)
#define ISP_COLOR_REPLACE4			(ISP_BASE + 0x17C)
#define ISP_COLOR_REPLACE5			(ISP_BASE + 0x180)
#define ISP_COLOR_REPLACE6			(ISP_BASE + 0x184)
#define ISP_COLOR_REPLACE7			(ISP_BASE + 0x188)
#define ISP_COLOR_REPLACE8			(ISP_BASE + 0x18C)
#define ISP_COLOR_REPLACE9			(ISP_BASE + 0x190)
#define ISP_COLOR_REPLACE10			(ISP_BASE + 0x194)
#define ISP_COLOR_REPLACE11			(ISP_BASE + 0x198)
#define ISP_COLOR_REPLACE12			(ISP_BASE + 0x19C)
#define ISP_COLOR_REPLACE13			(ISP_BASE + 0x1A0)
#define ISP_COLOR_REPLACE14			(ISP_BASE + 0x1A4)
#define ISP_COLOR_REPLACE15			(ISP_BASE + 0x1A8)
#define ISP_COLOR_REPLACE16			(ISP_BASE + 0x1AC)
#define ISP2_CTL				(ISP_BASE + 0x1EC)
#define ISP_CHANNEL_2_STATE			(ISP_BASE + 0x1F0)
#define ISP_CHANNEL_2_BA_OFFSET			(ISP_BASE + 0x1F4)
#define ISP_CHANNEL_2_ROW_RANGE			(ISP_BASE + 0x1F8)
#define ISP_CHANNEL_2_COL_RANGE			(ISP_BASE + 0x1FC)
#define ISP_CHANNEL_2_ADDR0			(ISP_BASE + 0x200)
#define ISP_CHANNEL_2_ADDR1			(ISP_BASE + 0x204)
#define ISP_CHANNEL_2_ADDR2			(ISP_BASE + 0x208)
#define ISP_CHANNEL_2_ADDR3			(ISP_BASE + 0x20C)
#define ISP_CHANNEL_2_ADDR4			(ISP_BASE + 0x210)
#define ISP_CHANNEL_2_ADDR5			(ISP_BASE + 0x214)
#define ISP_CHANNEL_2_ADDR6			(ISP_BASE + 0x218)
#define ISP_CHANNEL_2_ADDR7			(ISP_BASE + 0x21C)
#define ISP2_LSC_LUT_PORT			(ISP_BASE + 0x22C)
#define ISP2_LSC_PIX_INC			(ISP_BASE + 0x230)
#define ISP2_LSC_SCALING			(ISP_BASE + 0x234)
#define ISP2_LSC_CENTER0			(ISP_BASE + 0x238)
#define ISP2_LSC_CENTER1			(ISP_BASE + 0x23C)
#define ISP2_LSC_RST				(ISP_BASE + 0x240)
#define ISP2_NR_CONTROL				(ISP_BASE + 0x24C)
#define ISP2_DPC_THRESHOLD			(ISP_BASE + 0x254)
#define ISP2_CG_B_GAIN				(ISP_BASE + 0x25C)
#define ISP2_CG_G_GAIN				(ISP_BASE + 0x260)
#define ISP2_CG_R_GAIN				(ISP_BASE + 0x264)
#define ISP2_STAT_REGION_Y			(ISP_BASE + 0x26C)
#define ISP2_STAT_REGION_X			(ISP_BASE + 0x270)
#define ISP2_STAT_HIST_Y			(ISP_BASE + 0x274)
#define ISP2_STAT_HIST_X			(ISP_BASE + 0x278)
#define ISP2_WB_THRESHOLD			(ISP_BASE + 0x27C)
#define ISP2_CSC_OFFSET1			(ISP_BASE + 0x28C)
#define ISP2_CSC_OFFSET2			(ISP_BASE + 0x290)
#define ISP2_CSC_OFFSET3			(ISP_BASE + 0x294)
#define ISP2_CSC_Y_R			(ISP_BASE + 0x298)
#define ISP2_CSC_Y_G			(ISP_BASE + 0x29C)
#define ISP2_CSC_Y_B			(ISP_BASE + 0x2A0)
#define ISP2_CSC_CB_R			(ISP_BASE + 0x2A4)
#define ISP2_CSC_CB_G			(ISP_BASE + 0x2A8)
#define ISP2_CSC_CB_B			(ISP_BASE + 0x2AC)
#define ISP2_CSC_CR_R			(ISP_BASE + 0x2B0)
#define ISP2_CSC_CR_G			(ISP_BASE + 0x2B4)
#define ISP2_CSC_CR_B			(ISP_BASE + 0x2B8)
#define ISP2_CSC_CONTROL		(ISP_BASE + 0x2BC)
#define ISP2_GC_COEFF_0			(ISP_BASE + 0x2CC)
#define ISP2_GC_COEFF_1			(ISP_BASE + 0x2D0)
#define ISP2_GC_COEFF_2			(ISP_BASE + 0x2D4)
#define ISP2_GC_COEFF_3			(ISP_BASE + 0x2D8)
#define ISP2_GC_COEFF_4			(ISP_BASE + 0x2DC)
#define ISP2_GC_COEFF_5			(ISP_BASE + 0x2E0)
#define ISP2_GC_COEFF_6			(ISP_BASE + 0x2E4)
#define ISP2_GC_COEFF_7			(ISP_BASE + 0x2E8)
#define ISP2_GC_COEFF_8			(ISP_BASE + 0x2EC)
#define ISP2_GC_COEFF_9			(ISP_BASE + 0x2F0)
#define ISP2_GC_COEFF_10			(ISP_BASE + 0x2F4)
#define ISP2_GC_COEFF_11			(ISP_BASE + 0x2F8)
#define ISP2_GC_COEFF_12			(ISP_BASE + 0x2FC)
#define ISP2_GC_COEFF_13			(ISP_BASE + 0x300)
#define ISP2_GC_COEFF_14			(ISP_BASE + 0x304)
#define ISP2_GC_COEFF_15			(ISP_BASE + 0x308)
#define ISP2_OUT_FMT				(ISP_BASE + 0x314)
#define ISP2_OUT_ADDRY				(ISP_BASE + 0x318)
#define ISP2_OUT_ADDRU				(ISP_BASE + 0x31C)
#define ISP2_OUT_ADDRV				(ISP_BASE + 0x320)
#define ISP2_OUT_ADDR1UV			(ISP_BASE + 0x324)
#define ISP2_STAT_ADDR				(ISP_BASE + 0x32C)
#define ISP2_COLOR_REPLACE1			(ISP_BASE + 0x33C)
#define ISP2_COLOR_REPLACE2			(ISP_BASE + 0x340)
#define ISP2_COLOR_REPLACE3			(ISP_BASE + 0x344)
#define ISP2_COLOR_REPLACE4			(ISP_BASE + 0x348)
#define ISP2_COLOR_REPLACE5			(ISP_BASE + 0x34C)
#define ISP2_COLOR_REPLACE6			(ISP_BASE + 0x350)
#define ISP2_COLOR_REPLACE7			(ISP_BASE + 0x354)
#define ISP2_COLOR_REPLACE8			(ISP_BASE + 0x358)
#define ISP2_COLOR_REPLACE9			(ISP_BASE + 0x35C)
#define ISP2_COLOR_REPLACE10			(ISP_BASE + 0x360)
#define ISP2_COLOR_REPLACE11			(ISP_BASE + 0x364)
#define ISP2_COLOR_REPLACE12			(ISP_BASE + 0x368)
#define ISP2_COLOR_REPLACE13			(ISP_BASE + 0x36C)
#define ISP2_COLOR_REPLACE14			(ISP_BASE + 0x370)
#define ISP2_COLOR_REPLACE15			(ISP_BASE + 0x374)
#define ISP2_COLOR_REPLACE16			(ISP_BASE + 0x378)
#define ISP_FREEMODE_IMAGE_SIZE			(ISP_BASE + 0x398)
#define ISP_FREEMODE_SET			(ISP_BASE + 0x39C)
#define ISP_FREEMODE_ADDRESS			(ISP_BASE + 0x3A0)
#define AF_ENABLE				(ISP_BASE + 0x3A4)
#define AF_CTRL				(ISP_BASE + 0x3A8)
#define AF_WP0				(ISP_BASE + 0x3AC)
#define AF_WP1				(ISP_BASE + 0x3B0)
#define AF_WP2				(ISP_BASE + 0x3B4)
#define AF_WP3				(ISP_BASE + 0x3B8)
#define AF_WP4				(ISP_BASE + 0x3BC)
#define AF_WP5				(ISP_BASE + 0x3C0)
#define AF_WP6				(ISP_BASE + 0x3C4)
#define AF_WP7				(ISP_BASE + 0x3C8)
#define AF_WP8				(ISP_BASE + 0x3CC)
#define AF_FV0				(ISP_BASE + 0x3D0)
#define AF_FV1				(ISP_BASE + 0x3D4)
#define AF_FV2				(ISP_BASE + 0x3D8)
#define AF_FV3				(ISP_BASE + 0x3DC)
#define AF_FV4				(ISP_BASE + 0x3E0)
#define AF_FV5				(ISP_BASE + 0x3E4)
#define AF_FV6				(ISP_BASE + 0x3E8)
#define AF_FV7				(ISP_BASE + 0x3EC)
#define AF_FV8				(ISP_BASE + 0x3F0)
#define AF_TEN_THOD			(ISP_BASE + 0x3F4)
#define ISP_INT_STAT			(ISP_BASE + 0x400)

#endif

