#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# Lipeng<lipeng@actions-semi.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_VIDEO_OWL_CVBS) += cvbsc.o
obj-$(CONFIG_VIDEO_OWL_LCD) += lcdc.o
obj-$(CONFIG_VIDEO_OWL_EDP) += edpc.o
obj-$(CONFIG_VIDEO_OWL_DSI) += dsic.o
obj-$(CONFIG_VIDEO_OWL_DUMMY) += dummy_dispc.o
obj-$(CONFIG_VIDEO_OWL_HDMI) += hdmic/
