#
# OWL Display Subsystem Core
#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# Author: Lipeng<lipeng@actions-semi.com>
#
# Change log:
#	2015/8/8: Created by Lipeng.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += core.o ctrl.o de.o panel.o
