#
# Copyright (c) 2015 Actions Semi Co., Ltd.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += board.o power.o check_shell.o

obj-$(CONFIG_USBDOWNLOAD_GADGET) += gadget.o

obj-$(CONFIG_SPLASH_SCREEN) += splash.o
obj-$(CONFIG_ANDROID_RECOVERY) += recovery.o
obj-$(CONFIG_CHECK_KEY) += check_key.o
